
pipeline {
    agent any

    environment {
        EC2_PUBLIC_IP = '52.21.60.249'
        IMAGE_NAME    = 'inventory-backend'
        DOCKER_TAG    = 'latest'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'stack-backend',
                    url: 'https://github.com/kaviyarashugayu1997-maker/stack-application.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    sh "docker build -t ${IMAGE_NAME}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Run Container Test') {
            steps {
                sh "docker run --rm ${IMAGE_NAME}:${DOCKER_TAG}"
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(credentials: ['sshagent']) {

                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${EC2_PUBLIC_IP} '
                        sudo docker stop backend-app || true
                        sudo docker rm backend-app || true
                    '
                    """

                    sh """
                    scp -o StrictHostKeyChecking=no -r backend/* ubuntu@${EC2_PUBLIC_IP}:/home/ubuntu/app/backend
                    """

                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${EC2_PUBLIC_IP} '
                        cd /home/ubuntu/app/backend
                        sudo docker build -t ${IMAGE_NAME}:${DOCKER_TAG} .
                        sudo docker run -d --name backend-app -p 5000:5000 --restart always ${IMAGE_NAME}:${DOCKER_TAG}
                    '
                    """
                }
            }
        }
    }

    post {
        success {
            echo "DEPLOYMENT SUCCESSFUL: http://${EC2_PUBLIC_IP}:5000"
        }
        failure 
            echo "DEPLOYMENT FAILED"
        }
    }
}
